// 모든 페이지에 적용이 되는 레이아웃임.
import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/navbar";

export const metadata: Metadata = {
  title: "Poly의 대학생활",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" bg-blue-100">
        <header>
          <Navbar />
        </header>
        {children}
        <footer></footer>
      </body>
    </html>
  );
}
